SujetPoints = {
    "Je" : 0,
    "Tu" : 0,
    "Votre chère et tendre mère" : 1,
    "Votre père" : 0,
    "Ta famille" : 0,
    "Tes parents" : 0,
    "Tes ancêtres" : 2,
    "Votre descendance" : 0,
    "Votre trogne" : 0,
    "Ta face" : 0,
    "Ton chien" : 0,
    "Ton chat" : 0,
    "Ta croupe" : 0,
    "Tes petits-enfants" : 0,
    "Ton grouin" : 0,
    "Tes grands morts" : 0        
}

VerbePoints = {
    "est" : 1,
    "pue" : 3,
    "puent": 3,
    "achète": 2,
    "achètent": 2,
    "déteste": 2,
    "détestent": 2,
    "mange": 2,
    "mangent": 2,
    "fait corps neuf" : 5,
    "joue de la saqueboute": 3,
    "ratiboise": 3,
    "adore": 2,
    "aime": 2,
    "aiment": 2,
    "aime comme la colique" : 5,
    "s'extasie": 3,
    "détruit": 2,
    "casse": 3,
    "cassent": 3,
    "vulgarise": 2,
    "fait le mignard": 5,
    "parade": 2,
    "paradent": 2
}

ComplementPoints = {
    "toujours" : 1,
    "beaucoup" : 1,
    "pour" : 1,
    "la plupart" : 1,
    "à foison" : 5,
    "jamais" : 1,
    "à chaque fois": 2,
    "énormément" : 1,
    "comme à l'habitude" : 1,
    "avec" : 1,
    "puissamment" : 1,
    "devant" : 1,
    "derrière" : 1,
    "à côté" : 1
}

ConjonctionPoints = {
    "les truies" : 2,
    "des truies" : 1,
    "des moineaux": 1,
    "des bananes": 1,
    "les coureuses de remparts" : 5,
    "et": 1,
    "mais" : 1,
    "les chambres basses" : 5,
    "et puis" : 1,
    "les cloportes" : 2,
    "le sapajou" : 4,
    "en public" : 1,
    "comme jaja" : 1,
    "le bonobo" : 1,
    "la bistouquette" : 2,
    "le zgeg" : 1,
    "le kebab" : 1,
    "le saltimbanque" : 4,
    "la calotte de ses morts" : 1,
    "les selles" : 4,
    "la calebasse" : 5,
    "l'initié" : 1,
    "le guide": 1,
    "le préparateur en pharmacie": 1,
    "le président du club de Bridge": 3
}

BonusPoints = {
    "obsolète(s)": 3,
    "inutile(s)": 1,
    "nauséabond(es)": 4,
    "singé(e)": 2,
    "malade": 1,
    "pourri(e)": 1,
    "sec(s)": 1,
    "sèche(s)": 1,
    "eunuque": 4,
    "coprolithe(s)": 5,
    "orchidoclaste": 6,
    "gourgandine": 5,
    "votre gueux d'époux": 3,
    "vilain(e)": 2,
    "bougiron": 5,
    "bestiasse": 4,
    "engrogné(e)": 3,
    "carabiné(e)": 2,
    "claqué(e) au sol": 1,
    "chétif": 2,
    "chétive": 2,
    "minuscule": 1,
    "laid": 1,
    "moche(s)": 1,
    "magnifique": 1,
    "cruel(s)": 1,
    "cruelle(s)": 1
}

MotSpesPoints = {
    ", et vous êtes un laidron mais vous êtes bien bonne ": 6,
    ", Okaaay!": 6,
    "(...)": 0,
    ", machurat!": 3,
    ", sabrenas!": 4,
    ", mirabeau tonneau!": 2,
    ", et que trépasse si je faiblis!": 6,
    ", vil freluqué!": 2,
    ", fils de porchas!": 4,
    ", car il/elle n'est qu'un(e) caquet bon bec!": 5,
    "car il/elle n'a pas de dignité!": 2,
    ", calotte de poulpe!": 2,
    ", saltimbanque!": 3,
    ", paltoquet!": 4,
    ", et vous vulgarisez, vous vulgarisez.": 4
}